# Use the official Node.js 16 image
FROM node:16

# Create and change to the app directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY Source/backend/package*.json ./

# Install dependencies including nodemon
RUN npm install -g nodemon && npm install

# Copy the rest of the application code
COPY . .

# Expose port 5555 for the backend
EXPOSE 5555

# Start the application with nodemon
CMD ["nodemon", "index.js"]