version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/node:16
    working_directory: ~/repo

jobs:
  test:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Install Dependencies
          command: |
            cd Source
            npm install
      - run:
          name: Run Tests
          command: |
            cd Source
            npm test
     

  build-and-push-docker-image:
    docker:
      - image: circleci/node:14.18.0
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build Docker Image
          command: docker-compose build
      - run:
          name: Tag Frontend Docker Image
          command: docker tag project_frontend $DOCKERHUB_USERNAME/project_frontend:v1
      - run:
          name: Tag Backend Docker Image
          command: docker tag  project_backend $DOCKERHUB_USERNAME/project_backend:v1
      - run:
          name: Authenticate with Docker Hub
          command: echo "$DOCKERHUB_PASS" | docker login --username $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Push Docker Image to Docker Hub
          command: docker push $DOCKERHUB_USERNAME/project_frontend:v1
      - run:
          name: Push 
          command: docker push $DOCKERHUB_USERNAME/project_backend:v1

workflows:
  version: 2
  test-and-deploy:
    jobs:
    - build-and-push-docker-image
      requires:
        - test
